version: '3.1'
services:
  postgres:
    container_name: user
    image: postgres:14.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
